### ISSUE TITLE
canonical(secrets): SecretType's ANY wildcard is advertised on two API surfaces that always reject it

### ISSUE THREAD

**Issue by mrveiss** [mrveiss/AutoBot-AI#14974]
Introduced by #14957 (closes #13846). Filing rather than silently shipping, because the
choice is an architecture decision, not a bug with one right answer.

## What happened

#13846 required `ANY` to be preserved: *"`ANY` preserved — it is a genuine wildcard, not a
duplicate member, and must not be lost in consolidation"*. #14957 preserved it as a member of
the canonical `SecretType`.

`SecretType` is also the type of two API-facing pydantic fields:

* `SecretCreateRequest.type` — request
* `SecretModel.type` — response

So the regenerated public type now reads:

```
SecretType: "ssh_key" | "password" | "api_key" | "token" | "oauth_refresh_token"
          | "connector_oauth_token" | "certificate" | "database_url"
          | "infrastructure_host" | "other" | "any"
```

`autobot-frontend/src/types/generated/api.ts`

## Why it is not a functional bug

`"any"` is rejected at every surface that matters, and this is covered by tests:

* `SecretCreateRequest` has a `field_validator` that raises on `SecretType.ANY`, so
  `POST /secrets` returns 422 — nothing can be stored with type `"any"`.
* `GET /secrets/types` serves `SecretType.concrete()`, which excludes it, so the picker
  never offers it.
* Because nothing can be stored, no response can ever carry it either.

## Why it is still worth deciding

The **declared** type is wider than the **accepted** type. A frontend developer reading
`api.ts` sees `"any"` as a valid secret type on both request and response, and the compiler
agrees, right up until the server returns 422. A type that permits what the endpoint always
rejects is the kind of thing that gets "fixed" later by someone relaxing the validator.

## Options

**Option A — leave it (recommended).** One canonical enum, wildcard included, exactly as
#13846 asked. The narrowing lives in the validator and in `concrete()`, both tested. Cost: the
generated type is wider than reality on two fields.

**Option B — narrow the API fields to the concrete taxonomy.** Keep one enum, but give the two
API fields a schema listing only `SecretType.concrete()`. Cost: the narrowing must be
*derived* from the enum, never hand-listed, or it becomes exactly the drift #13846 was filed
about — and the reliable mechanisms for this (a derived `Literal`, or `json_schema_extra`
beside a `$ref`) are respectively mypy-hostile and not guaranteed to survive
`openapi-typescript`. Needs verifying against a real schema dump, not reasoning.

**Option C — move the wildcard out of the enum.** `SecretType` becomes purely the taxonomy;
the requirement layer expresses "any" as a separate sentinel. Cost: contradicts #13846's
explicit AC, and reintroduces a second vocabulary in the requirement layer — the shape the
whole issue existed to remove.

**Recommendation: A**, with this issue kept open as the record of the trade-off. B is worth
doing only if someone verifies the generated output rather than predicting it.

## Do not

Do not relax or delete the `_reject_the_wildcard` validator to make the type "honest". The
validator is the thing keeping `"any"` out of the `secrets.type` column.

Refs #13846, #14957

**Comment by mrveiss** [comment]
Delivered by PR #15010, merged to `Dev_new_gui` as `61f79f032`.

**This issue recommended Option A (leave it) and asked to stay open as the record of the trade-off. #15010 implemented Option B instead — and the condition this issue set for B has now been met.** The wording was: *"B is worth doing only if someone verifies the generated output rather than predicting it."* That verification exists, against a real dump rather than reasoning:

`autobot-frontend/src/types/generated/api.ts:92069` on the merged base —

```ts
type: "ssh_key" | "password" | "api_key" | "token" | "oauth_refresh_token"
    | "connector_oauth_token" | "certificate" | "database_url"
    | "infrastructure_host" | "other";
```

Ten concrete kinds, **no `"any"`**. The narrowing survived `openapi-typescript`, which was the specific risk this issue said could not be predicted.

The two costs this issue warned about are both avoided:

| Warned cost | Outcome |
|---|---|
| "the narrowing must be *derived* from the enum, never hand-listed, or it becomes exactly the drift #13846 was filed about" | `api/schemas_secrets.py` builds it as `[member.value for member in SecretType.concrete()]`. A kind added to the enum appears here with no second edit. |
| "a derived `Literal` … is mypy-hostile" | Sidestepped — `WithJsonSchema` narrows the *advertised* schema beside the real annotation, so no `Literal` is synthesised and mypy still sees `SecretType`. |
| "do not relax or delete the `_reject_the_wildcard` validator" | Untouched and still enforcing; it moved to `api/schemas_secrets.py` with the annotation it belongs to. |

`SecretType` itself still carries `"any"` at `api.ts:92261`, exactly as #13846 requires — one canonical enum, wildcard included. What changed is only what the two storable fields *advertise*.

**One thing I could not confirm, stated rather than glossed:** of the two Python field sites now using `StorableSecretType` (`api/schemas_system.py:3516` and `:3531`), only `SecretCreateRequest` appears in the generated types. `SecretModel` is absent from `api.ts` entirely, so I cannot show its narrowing in a dump the way I can for the other. That is consistent with it not being referenced by any served response, but I have not proven that, and it is not something this issue's criteria turn on.

Closing: the wildcard is no longer advertised on the surface that publishes it, the narrowing is derived rather than hand-listed, and the validator that keeps `"any"` out of the `secrets.type` column is intact.
