### ISSUE TITLE
fix(frontend): resolve 5 TypeScript errors in PluginsView and SettingsView

### ISSUE THREAD

**Issue by mrveiss** [mrveiss/AutoBot-AI#9477]
## Context

After rebasing PR #9407 onto Dev_new_gui, discovered 5 TypeScript errors that exist in Dev_new_gui itself (not introduced by the PR).

### PluginsView.vue (3 errors)
```
src/views/PluginsView.vue(364,38): error TS2339: Property 'trust_tier' does not exist on type '{ name: string; version: string; ... }'.
src/views/PluginsView.vue(365,38): error TS2339: Property 'trust_tier' does not exist on type '{ name: string; version: string; ... }'.
src/views/PluginsView.vue(366,53): error TS2339: Property 'trust_tier' does not exist on type '{ name: string; version: string; ... }'.
```

**Root cause:** The plugin type interface is missing the `trust_tier` property, but the template uses it.

### SettingsView.vue (2 errors)
```
src/views/SettingsView.vue(102,17): error TS2322: Type '"mobile"' is not assignable to type '"tools" | "sort" | ... | "user-circle"'.
src/views/SettingsView.vue(306,21): error TS2322: Type '"mobile"' is not assignable to type '"tools" | "sort" | ... | "user-circle"'.
```

**Root cause:** The icon component doesn't recognize 'mobile' as a valid icon name.

## Action Required

1. Add `trust_tier?: string` to the plugin type interface in PluginsView.vue
2. Either add 'mobile' to the allowed icon types or use a different icon in SettingsView.vue

## Related

- PR #9407
- Discovered during vue-tsc baseline update from 240 → 245

**Comment by mrveiss** [comment]
Closed — verified already resolved and merged to Dev_new_gui. `vue-tsc --noEmit -p tsconfig.app.json` reports zero errors referencing PluginsView/SettingsView. Commit `87b2708d4`. Verified present in current tree; issue was left open after merge.
