### ISSUE TITLE
fix(ci): frontend-tests failures on main (post-#9512 uv deps bump)

### ISSUE THREAD

**Issue by mrveiss** [mrveiss/AutoBot-AI#9693]
## Context

Frontend test suite is failing on main branch after PR #9512 merged (uv dependency bump: starlette 1.0.1, aiohttp 3.14.0).

## Acceptance Criteria
- [ ] Identify root cause of frontend test failures
- [ ] Fix or update failing tests
- [ ] Verify all frontend tests pass on main

## Paperclip Issue
[MVA-3886](/MVA/issues/MVA-3886)

**Comment by mrveiss** [comment]
## Root Cause Identified

**Issue:** Frontend tests failing with 60+ TypeScript compilation errors after PR #9512 merged.

**Root Cause:** PR #9512 modified backend API schemas (added type annotations) but didn't regenerate the frontend TypeScript types in `src/types/generated/api.ts`.

**Fix Required:**
1. Start backend server on http://127.0.0.1:8001
2. Run `npm run gen:types` in autobot-frontend/
3. Commit the regenerated `src/types/generated/api.ts`

**Details:** See [Paperclip MVA-3886](/MVA/issues/MVA-3886) for complete analysis and fix instructions.

**Status:** Root cause documented, blocked on dev environment availability for implementation.

**Comment by mrveiss** [comment]
**Root cause identified** (still red on Dev_new_gui HEAD as of 2026-06-08; surfaced on promotion PR #9721). The `frontend-tests` failure is in the **\"Run frontend linting\"** step — eslint exits 1 on these **errors** (not the uv bump):

- `no-restricted-imports` — deprecated `@/composables/useApi` imported (e.g. lines 79 and 91 in offending files). `useApi` is deprecated per #6487 → migrate to `useFetchEndpoint` / `useApiClient()`.
- `vue/no-unused-vars` — `'idx' is defined but never used` (`FailedVectorizationsManager.stories.ts:144:31`)
- `no-console` — `Unexpected console statement` (e.g. `:204:5`, `:148:5`)

Fix = migrate the deprecated `useApi` imports + remove unused vars/console statements; eslint then passes. (Lint errors, not test failures.)

**Comment by mrveiss** [comment]
**Bug sweep 2026-06-10 → NEEDS-REPRO.** Environment/CI-specific (post starlette/aiohttp bump in #9512) with no captured failure output. Please attach the failing job log (the actual test names + tracebacks) and confirm whether it still reproduces on current `main`/`Dev_new_gui` after the later dependency work — several deps moved since #9512.

**Comment by mrveiss** [comment]
Closed — merged to Dev_new_gui (PR #10078, commit `c3637ca26`).

**Criteria met:** `npm run test:unit` → 105 files, 1781 passed / 1 skipped / 0 failed / 0 unhandled errors (was 89 failed + 3 uncaught); `npm run test:integration` → 28/28; `npm run lint` → exit 0. 8 real runtime bugs fixed at root cause (Pinia-after-teardown timer via `whenPiniaReady`, dead Vite-7 integration config, matchMedia mockReset wipe, double MSW interception, etc.).

After #9724 merged, its icon-helper IconName migration had landed a 19-test regression (helpers migrated, tests not); aligned those in commit `22eb0ea0c`. smoke-test green on the PR.

Discoveries surfaced (already filed by parallel work): #10085 (LiveEventService Pinia timer). Part of umbrella #9924.
