### ISSUE TITLE
Bug: Template execute passes invalid 'metadata' kwarg to WorkflowStep

### ISSUE THREAD

**Issue by mrveiss** [mrveiss/AutoBot-AI#1338]
## Problem

The `_convert_template_steps()` function in `api/templates.py:531` (introduced by #1272 fix) passes a `metadata={...}` keyword argument to the `WorkflowStep` dataclass constructor, but the `WorkflowStep` class in `services/workflow_automation/models.py` has no `metadata` field.

This causes **every** template execution to fail with:
```
WorkflowStep.__init__() got an unexpected keyword argument 'metadata'
```

The "Run Now" and "Run Workflow" buttons on `/automation` do nothing — the API returns HTTP 500.

## Root Cause

Regression from #1272 fix. The `metadata` dict was added to preserve agent_type/action/inputs info, but the target dataclass doesn't accept it.

## Fix

Removed the `metadata` keyword argument from the `WAStep()` constructor call in `_convert_template_steps()`. The metadata info was already captured in the `explanation` field.

**File:** `autobot-backend/api/templates.py` — removed lines 531-535.

## Verification

Tested both `reddit_monitor_reply` and `release_announcement_blast` templates — both execute successfully after the fix. Deployed to .20.

## Impact

All template execution was broken — community growth templates, security scans, research workflows, etc.
