### ISSUE TITLE
test(slm): process_divergence_test fails only in a combined run — cross-test pollution in the SLM suite

### ISSUE THREAD

**Issue by mrveiss** [mrveiss/AutoBot-AI#15466]
Found while adding a health probe (PR #15465); pre-existing on `Dev_new_gui`, so filed rather than folded in.

## Reproduction

```
cd autobot-slm-backend
python3 -m pytest -q tests/services/process_divergence_test.py      # 23 passed
python3 -m pytest -q -k "health" .                                   # 2 failed, 115 passed
```

The two that fail only in the combined run:

- `test_component_divergence_healthy_when_process_started_after_newest_file`
- `test_component_divergence_multi_unit_second_unit_stale_is_not_healthy`

Both pass in isolation. Verified on `origin/Dev_new_gui` at `60f35446e3` with no local changes, so it is not introduced by any open PR.

## Why it matters beyond the two tests

A test that passes alone and fails in company is not reporting on the code — it is reporting on whatever ran before it. Two consequences, and the second is the expensive one:

1. These two assertions currently protect nothing, because a genuine regression in process-divergence detection is indistinguishable from the pollution.
2. It trains people to re-run CI until green. This repo has already paid for that pattern once — #14157 was a concurrency test that failed on runner contention, and the fix was to assert the property directly rather than to loosen the threshold.

The two tests concern `healthy`/`not healthy` divergence verdicts, which is the same subsystem the deploy work has been touching, so a silently-unprotected assertion here is worse than average.

## What is needed

- [ ] Identify the polluting state — likely a module-level cache, a patched singleton, or a mocked clock left installed past its test
- [ ] Fix the leak at its source, scoped to the test that installs it (install and remove in the same `try/finally`), rather than adding a reset fixture to the victim
- [ ] Both tests pass in isolation **and** under `-k "health"` and a full-suite run
- [ ] A guard, if the leak is a shared singleton: the repo already has `repo_tests/sys_modules_leak_guard.py` for the `sys.modules` case — check whether this is the same class and extend it if so

## Related

- #14157 — a timing-based test that failed on contention; same "green by re-running" failure mode
- PR #15465 — where this surfaced

**Comment by mrveiss** [comment]
## Root-caused, not yet fixed — recording what it is and what it is not

Chased this while fixing #15065 (a different leak in the same package). The failure is no longer "two tests fail together":

```
AttributeError: module 'services' has no attribute 'process_divergence'
```

`process_divergence_test.py` patches by string — `patch("services.process_divergence._service_active_since_epoch", ...)`. `mock.patch` resolves that target at **call** time, not at import time. So the module-level `from services.process_divergence import (...)` at the top of the file can succeed, and the patch can still fail later, if anything has replaced `sys.modules["services"]` in between. The two failing tests are exactly the two that patch by string.

That also explains the signature I filed it with: passes alone, fails in company, and the code under test is fine.

## What it is not

Four bisect results, each a separate run:

| selection | failures |
|---|---|
| `tests/api/ tests/services/` | 0 |
| `tests/` (whole tree) | 0 |
| `api/` + the test file | 0 |
| `services/` + the test file | 0 |
| **`.` (full root)** | **2** |

And none of the four files that touch `sys.modules["services"]` reproduces it when paired directly with the test file: `test_llm_secrets.py`, `test_deploy_artifacts_lockstep.py`, `test_role_registry.py`, `test_real_service_modules_14307.py`.

So it is an **ordering interaction across the full selection**, not one polluter that can be pointed at. Pinning it needs a real bisect over collection order, which is more runs than I could justify in one pass.

## A related observation worth separating

`test_llm_secrets.py` installs a bare `types.ModuleType("services")` at module level — no `__path__`, so nothing under it can be imported afterwards — and it is **on** `repo_tests/sys_modules_leak_baseline.txt`.

Being on the baseline stops the guard failing the run. It does not stop the leak breaking other tests. Both were true here and only one was visible, which is worth keeping in mind when reading that baseline as a list of "known and therefore fine".

I drafted a fix for it (try the real package first; give any fallback a `__path__`) and **reverted it** — it did not fix these two failures, and an unverified change riding an unrelated PR is not an improvement. It is still probably worth doing on its own merits.

## Suggested fix, once the polluter is pinned

Two independent options, and the second is worth doing regardless:

1. Fix whatever replaces `sys.modules["services"]` to install and remove in the same `try/finally`.
2. Make the test immune: `patch.object(process_divergence, "_service_active_since_epoch", ...)` against the already-imported module object, rather than resolving a dotted string at call time. That removes the dependency on `sys.modules` being intact and is the more robust pattern for a module the test has already imported.

**Comment by mrveiss** [comment]
Stale-issue sweep (never auto-closed — Dev_new_gui wasn't GitHub's default branch at merge time). Leaving **open** — no PR delivers this.

The listed PR, #15482, fixes a different issue (#15065, a `python_multipart` stub shadowing the real package) and its own body states plainly: "What this does NOT fix — #15466 ... is a separate cause, confirmed by running it against this branch: still 2 failures." `gh pr view 15482 --json closingIssuesReferences` returns empty.

A follow-up comment on this issue root-causes the actual pollution (`mock.patch("services.process_divergence...")` resolving against a `sys.modules["services"]` shadowed by an unrelated test) but explicitly says "Root-caused, not yet fixed." No later PR references or fixes it.
