### ISSUE TITLE
bug(llm): AnthropicProvider betas forwarded to wrong SDK endpoint + temperature not enforced for thinking

### ISSUE THREAD

**Issue by mrveiss** [mrveiss/AutoBot-AI#3582]
## Root cause

Two bugs in `autobot-backend/llm_providers/anthropic_provider.py` introduced in PR #3575.

### Bug 1 — betas forwarded to wrong SDK endpoint

`_build_api_kwargs` passes `betas` through into `client.messages.create(**kwargs)`. The standard Anthropic SDK endpoint does not accept a `betas` parameter — raises `TypeError: unexpected keyword argument 'betas'`. Must go via `client.beta.messages.create(betas=[...])` or be converted to `extra_headers["anthropic-beta"]`.

### Bug 2 — temperature not enforced to 1 when thinking is enabled

Anthropic API returns HTTP 400 if `temperature != 1` when extended thinking is active. `LLMRequest.temperature` defaults to `0.7`. `_build_request_kwargs` does not auto-coerce to `1` when `api_kwargs` contains a `"thinking"` key.

## Fix

In `_build_request_kwargs`, when `api_kwargs.get("thinking")` is truthy:
1. Extract `betas` from kwargs and convert to `extra_headers["anthropic-beta"]` (comma-joined), then remove from main kwargs.
2. Force `kwargs["temperature"] = 1`.

Reported by code review of PR #3575.
