### ISSUE TITLE
test: llc/tests conftest teardown leaves the real knowledge package without its imported children — 4 cognifiers tests red in CI, green alone

### ISSUE THREAD

**Issue by mrveiss** [mrveiss/AutoBot-AI#13386]
## Summary

`autobot-backend/knowledge/pipeline/cognifiers/cognifiers_test.py::TestContextGeneratorEnabled` (4 tests) is red on `Dev_new_gui` and red in CI, but green when the file is run alone. The cause is in a different directory's conftest: `autobot-backend/llc/tests/conftest.py` restores the `knowledge` package on package teardown in a way that leaves the real package without its already-imported children bound as attributes.

Found while fixing the `llc/tests` slice of #13162 (PR #13385). Out of that PR's four assigned directories, so filed rather than fixed there.

## Reproduction

```
export SLM_SECRET_KEY=throwaway SLM_ENCRYPTION_KEY=x
python3 -m pytest autobot-backend/llc/tests/test_heartbeat_context.py \
  autobot-backend/knowledge/pipeline/cognifiers/cognifiers_test.py -q
```

```
FAILED .../cognifiers_test.py::TestContextGeneratorEnabled::test_enriches_chunks
FAILED .../cognifiers_test.py::TestContextGeneratorEnabled::test_cache_hit_skips_summary_llm_call
FAILED .../cognifiers_test.py::TestContextGeneratorEnabled::test_llm_failure_sets_has_context_false
FAILED .../cognifiers_test.py::TestContextGeneratorEnabled::test_enriched_content_format
```

The same file alone: `57 passed`.

## Mechanism

1. `llc/tests/conftest.py` installs a hollow `knowledge` package stub whose `__path__` points at the real directory. At that moment the real `knowledge` has not been imported, so the snapshot records `None` as the pre-stub state.
2. `cognifiers_test.py` is collected next. `from knowledge.pipeline... import X` resolves through the stub's `__path__`, so `sys.modules["knowledge.pipeline"]` is created and `pipeline` is bound as an attribute **on the stub**.
3. The llc package fixture tears down and, because the recorded prior state was `None`, pops `knowledge` from `sys.modules` entirely.
4. The cognifiers tests then run. `patch("knowledge.pipeline.cognifiers...")` triggers a fresh real import of `knowledge`, whose PEP 562 `__getattr__` raises for any name outside `__all__`:

```
AttributeError: module 'knowledge' has no attribute 'pipeline'
knowledge/__init__.py:82: AttributeError
```

`sys.modules["knowledge.pipeline"]` still exists, but the import machinery only sets the parent attribute during an actual load, so the freshly imported parent never gets it back.

## Suggested fix

When a package entry is swapped or removed in `sys.modules`, the already-imported children have to be re-attached to whatever object ends up in its place — the same parent-bind that `autobot-backend/conftest.py`'s `_real_load_and_bind` already performs for exactly this reason (#11532/#11618). A shared helper that both conftests call would be better than a third hand-rolled copy.

Not a production defect: `knowledge/__init__.py`'s lazy `__getattr__` is correct, and the cognifier code is correct. This is harness-only.

## Acceptance criteria

- [ ] The four `TestContextGeneratorEnabled` tests pass when collected in the same session as `autobot-backend/llc/tests/`, using the reproduction command above
- [ ] `autobot-backend/llc/tests/conftest.py` restores the `knowledge` package on teardown with its already-imported children still bound as attributes, rather than popping the package from `sys.modules`
- [ ] The `llc/tests` suite still passes on its own, and `cognifiers_test.py` still passes on its own — neither direction is traded for the other
- [ ] The fix addresses the recorded-prior-state-is-`None` path described in the Mechanism section, rather than reordering collection or renaming to dodge the interaction
- [ ] A test covers the cross-directory interaction itself, so a future conftest change that reintroduces it fails rather than silently returning the suite to red-in-CI-green-alone

**Comment by mrveiss** [comment]
Re-checked against merged base (`cf2d29d54e`) — **the symptom is fixed, but this issue should be rescoped rather than closed: two of its five criteria are demonstrably unmet.**

The failure this issue was filed against was re-diagnosed on the issue itself and fixed elsewhere: `autobot_shared/ssot_config.py:1952` now declares `context_summary_ttl_days: int = Field(default=30, ...)`, and the `int()` parse at `knowledge/pipeline/cognifiers/context_generator.py:51-55` is gone (`fd1dcf92c2`, #13656). Victim 2 (`rag_service_kb_synthesis_test`) was addressed by `ebbeeebd28` (#13459).

| AC | Status | Evidence |
|---|---|---|
| 1 — four tests pass in a combined session | UNVERIFIABLE | A runtime observation. The issue comment reports shard 3 going 6→0 after #13656, but that is a CI reading, not something a diff shows. |
| 2 — `llc/tests/conftest.py` restores `knowledge` **with children bound, rather than popping** | **UNMET** | `autobot-backend/llc/tests/conftest.py:476-486` — `_restore()` still does `if prior is None: sys.modules.pop(key, None)`. The `_rebind_all_submodules()` call at `:486` cannot cover that path: `_rebind_submodules` at `:345-347` returns immediately when `sys.modules.get(parent_key)` is `None`. And `knowledge.pipeline` is **not** in `_SCOPED_STUB_KEYS` (`:69-77`), so it survives the pop. The orphaning path this issue names is intact. |
| 3 — both directions still pass alone | UNVERIFIABLE | Requires a run. |
| 4 — the fix addresses the prior-state-is-`None` path | **UNMET** | The fix that landed (#13656) is a config typing change. It does not touch that path at all — it removed the *trigger*, not the mechanism. |
| 5 — a test covers the cross-directory interaction | **UNMET** | No file under `repo_tests/` references both `llc/tests` and the cognifiers. The `sys_modules` leak guard compares module identity, not parent attributes — #13596 says so explicitly — so it does not cover this. |

The distinction that matters: #13656 removed the input that tripped the teardown bug. The teardown bug is still there, and the next stub whose prior state is `None` will orphan its children the same way.

Recommend one of: (a) rescope onto migrating `llc/tests/conftest.py` to `StubSet` — it is the fifth hand-roller, adjacent to #13596's four; or (b) rewrite the ACs against the config root cause and close. Ticking the current boxes would be a false record either way.
